package com.xworkz.collections.boot;

import java.util.Collection;
import java.util.TreeSet;

public class MallRunner {
	public static void main(String[] args) {
		String mall1="orionMall";
		String mall2="royalMeenakshi";
		String mall3="gopalanMall";
		String mall4="mantriMall";
		String mall5="totalMall";
		String mall6="forum";
		String mall7="phoenix";
		String mall8="bangaloreCentral";
		String mall9="collectionUB";
		String mall10="GarudaMall";
		String mall11="inorbitMall";
		String mall12="leelaGalleria";
		String mall13="cosmosMall";
		String mall14="mtMall";
		String mall15="parkSquareMall";
		String mall16="luluMall";
		String mall17="dlfMall";
		String mall18="sarathMall";
		String mall19="zsquareMall";
		String mall20="worldTradeParkMall";
		String mall21="vr";
		String mall22="ub";
		String mall23="phoenixMarketcity";
		String mall24="commercial";
		String mall25="iconsiam";
		String mall26="funRepublic";
		String mall27="elanteMall";
		String mall28="dlfMall";
		String mall29="lotusMall";
		String mall30="sujana";
		String mall31="magnetoMall";
		String mall32="southCityMall";
		String mall33="prozoneMall";
		String mall34="alpha";
		String mall35="greatIndia";
		String mall36="citywalk";
		String mall37="kochi";
		String mall38="luckyOne";
		String mall39="emporium";
		String mall40="sarath";
		
		Collection<String>collection=new TreeSet();
		collection.add(mall40);
		collection.add(mall39);
		collection.add(mall38);
		collection.add(mall37);
		collection.add(mall36);
		collection.add(mall35);
		collection.add(mall34);
		collection.add(mall33);
		collection.add(mall32);
		collection.add(mall31);
		collection.add(mall30);
		collection.add(mall29);
		collection.add(mall28);
		collection.add(mall27);
		collection.add(mall26);
		collection.add(mall25);
		collection.add(mall24);
		collection.add(mall23);
		collection.add(mall22);
		collection.add(mall21);
		collection.add(mall20);
		collection.add(mall19);
		collection.add(mall18);
		collection.add(mall17);
		collection.add(mall16);
		collection.add(mall15);
		collection.add(mall14);
		collection.add(mall13);
		collection.add(mall12);
		collection.add(mall11);
		collection.add(mall10);
		collection.add(mall9);
		collection.add(mall8);
		collection.add(mall7);
		collection.add(mall6);
		collection.add(mall5);
		collection.add(mall4);
		collection.add(mall3);
		collection.add(mall2);
		collection.add(mall1);
		System.out.println(collection.size());
		collection.clear();
		System.out.println("After the clear...........");
		System.out.println(collection.size());
		
	}
}
